<a href="https://colab.research.google.com/github/lacteolus/pytorch_fundamentals/blob/master/00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


## Tensors

### Scalar

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

### Vector

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

### Matrix

In [8]:
matrix = torch.tensor([[7, 7], [7, 7]])
matrix

tensor([[7, 7],
        [7, 7]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

## Tensor

In [11]:
tensor = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
tensor.ndim

3

In [13]:
tensor.shape

torch.Size([1, 3, 3])

In [14]:
tensor[0, 1]

tensor([4, 5, 6])

In [15]:
tensor[0][1]

tensor([4, 5, 6])

### Random tensors

In [16]:
rnd_tensor = torch.rand(2, 3, 4)
rnd_tensor

tensor([[[0.0507, 0.2282, 0.7660, 0.4646],
         [0.9800, 0.5590, 0.4768, 0.9500],
         [0.6142, 0.8850, 0.0378, 0.0153]],

        [[0.3111, 0.8532, 0.4995, 0.7674],
         [0.8769, 0.1041, 0.4825, 0.7249],
         [0.1631, 0.4167, 0.7172, 0.8543]]])

In [17]:
rnd_tensor.ndim

3

In [18]:
rnd_tensor.shape

torch.Size([2, 3, 4])

In [19]:
img_tensor = torch.rand(size=(3, 200, 200))
img_tensor

tensor([[[7.2082e-01, 7.3915e-01, 6.8625e-01,  ..., 2.6586e-01,
          9.8726e-02, 5.1784e-01],
         [8.5382e-01, 8.7187e-01, 8.4516e-02,  ..., 8.7783e-01,
          7.8654e-01, 1.6244e-01],
         [9.5578e-02, 3.5135e-01, 4.3556e-01,  ..., 4.8182e-01,
          6.2323e-01, 3.3464e-01],
         ...,
         [5.5674e-02, 6.8056e-01, 5.9714e-01,  ..., 5.1661e-01,
          7.9081e-01, 4.9223e-02],
         [7.9676e-01, 2.4081e-01, 1.1052e-02,  ..., 6.2790e-02,
          6.5945e-01, 6.3795e-04],
         [3.7957e-03, 6.3379e-02, 9.7713e-01,  ..., 3.9882e-01,
          6.4168e-01, 4.2326e-02]],

        [[9.8215e-01, 1.3440e-01, 6.4491e-02,  ..., 9.8284e-01,
          6.4815e-02, 4.2886e-01],
         [3.6609e-01, 5.9562e-01, 6.8277e-01,  ..., 3.1573e-01,
          8.6145e-01, 8.2160e-01],
         [3.9090e-01, 5.9872e-01, 9.5910e-01,  ..., 3.4943e-01,
          3.5577e-01, 3.2067e-02],
         ...,
         [8.6544e-01, 5.1430e-01, 5.7839e-01,  ..., 4.6533e-01,
          8.966

In [20]:
img_tensor.ndim, img_tensor.shape

(3, torch.Size([3, 200, 200]))

In [21]:
img_tensor[0, 0]

tensor([0.7208, 0.7391, 0.6863, 0.0877, 0.8546, 0.5720, 0.4437, 0.7060, 0.7219,
        0.0307, 0.2009, 0.8059, 0.3666, 0.1863, 0.0905, 0.2316, 0.4074, 0.0744,
        0.4532, 0.4242, 0.0859, 0.2640, 0.2726, 0.7846, 0.1766, 0.6821, 0.2011,
        0.4479, 0.1624, 0.3288, 0.4942, 0.8995, 0.9857, 0.9091, 0.3228, 0.2629,
        0.5401, 0.2282, 0.9874, 0.5077, 0.7144, 0.5487, 0.5202, 0.5471, 0.7761,
        0.9901, 0.5625, 0.8335, 0.6639, 0.2501, 0.2913, 0.7074, 0.0459, 0.9933,
        0.8698, 0.7045, 0.0884, 0.0609, 0.0521, 0.4826, 0.6494, 0.9105, 0.7357,
        0.9217, 0.3209, 0.1721, 0.1257, 0.5381, 0.6672, 0.2880, 0.0820, 0.9045,
        0.4388, 0.3483, 0.7692, 0.2368, 0.4361, 0.7377, 0.6271, 0.7854, 0.4356,
        0.7134, 0.5426, 0.4074, 0.0665, 0.1242, 0.8814, 0.2834, 0.2481, 0.2230,
        0.8151, 0.5492, 0.7419, 0.9235, 0.8300, 0.9039, 0.6702, 0.8542, 0.9465,
        0.2416, 0.3486, 0.0434, 0.1678, 0.2957, 0.6397, 0.0452, 0.8365, 0.3803,
        0.6920, 0.0964, 0.9354, 0.0576, 

### Ones and zeroes

In [22]:
ones = torch.ones(size=(2, 2))
ones

tensor([[1., 1.],
        [1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
zeros = torch.zeros(size=(2, 2))
zeros

tensor([[0., 0.],
        [0., 0.]])

### Ranges and tensor like

In [25]:
range_tensor = torch.arange(0, 10, 2)
range_tensor

tensor([0, 2, 4, 6, 8])

In [26]:
like_tensor = torch.zeros_like(range_tensor)
like_tensor

tensor([0, 0, 0, 0, 0])

### Tensor datatypes

In [27]:
float_tensor = torch.tensor([2, 3, 4], dtype=torch.float32)
float_tensor

tensor([2., 3., 4.])

In [28]:
bool_tensor = torch.tensor([0, 3, 4], dtype=torch.bool)
bool_tensor

tensor([False,  True,  True])

In [29]:
int_tensor = float_tensor.type(torch.int32)
int_tensor.dtype

torch.int32

In [30]:
int_tensor

tensor([2, 3, 4], dtype=torch.int32)

In [31]:
int_tensor.device

device(type='cpu')

### Tensors operations

In [32]:
a_tensor = torch.tensor([1, 2, 3])

In [33]:
a_tensor + 10

tensor([11, 12, 13])

In [34]:
a_tensor * 10

tensor([10, 20, 30])

In [35]:
a_tensor - 10

tensor([-9, -8, -7])

In [36]:
a_tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [38]:
b_tensor = torch.tensor([4, 5, 6])

In [39]:
# element wise
a_tensor * b_tensor

tensor([ 4, 10, 18])

In [40]:
# matrix
torch.matmul(a_tensor, b_tensor)

tensor(32)

In [49]:
tensor_a = torch.tensor([[1, 2], 
                          [3, 4], 
                          [5, 6]])

In [50]:
tensor_a.shape

torch.Size([3, 2])

In [45]:
tensor_b = torch.tensor([[7, 10], 
                          [8, 11], 
                          [9, 12]])

In [46]:
tensor_b.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [47]:
tensor_b.T.shape

torch.Size([2, 3])

In [52]:
tensor_a @ tensor_b.T

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Tensor aggregation

In [66]:
tensor = torch.arange(1, 100, 3)

In [67]:
tensor.min()

tensor(1)

In [68]:
tensor.max()

tensor(97)

In [69]:
tensor = tensor.type(torch.float32)
torch.mean(tensor)

tensor(49.)

In [70]:
tensor.sum()

tensor(1617.)

In [71]:
tensor.argmin()

tensor(0)

In [72]:
tensor.argmax()

tensor(32)

In [73]:
tensor[13]

tensor(40.)

### Reshape, stack, squeeze, unsqueeze

In [94]:
tensor = torch.arange(1, 10)

In [75]:
tensor, tensor.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [82]:
new_tensor = tensor.reshape(3, 3)
new_tensor, new_tensor.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]), torch.Size([3, 3]))

In [95]:
v_tensor = tensor.view(1, 9)
v_tensor

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [96]:
v_tensor[:, 0] = 5
v_tensor

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [97]:
tensor

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
s_tensor = torch.stack([tensor, tensor], dim=1)
s_tensor

tensor([[5, 5],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5],
        [6, 6],
        [7, 7],
        [8, 8],
        [9, 9]])

In [100]:
s_tensor = torch.stack([tensor, tensor], dim=0)
s_tensor

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [109]:
tensor = torch.tensor([[1, 2, 3]])
tensor.shape

torch.Size([1, 3])

In [111]:
ss_tensor = torch.squeeze(tensor)
ss_tensor
ss_tensor.shape

torch.Size([3])

In [116]:
u_tensor = torch.unsqueeze(ss_tensor, dim=1)
u_tensor

tensor([[1],
        [2],
        [3]])