<a href="https://colab.research.google.com/github/lacteolus/pytorch_fundamentals/blob/master/00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


## Tensors

### Scalar

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

### Vector

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

### Matrix

In [8]:
matrix = torch.tensor([[7, 7], [7, 7]])
matrix

tensor([[7, 7],
        [7, 7]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

## Tensor

In [11]:
tensor = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
tensor.ndim

3

In [13]:
tensor.shape

torch.Size([1, 3, 3])

In [14]:
tensor[0, 1]

tensor([4, 5, 6])

In [15]:
tensor[0][1]

tensor([4, 5, 6])

### Random tensors

In [16]:
rnd_tensor = torch.rand(2, 3, 4)
rnd_tensor

tensor([[[0.1060, 0.2138, 0.1765, 0.7497],
         [0.4821, 0.6976, 0.6348, 0.2100],
         [0.5607, 0.0868, 0.2533, 0.0562]],

        [[0.9360, 0.6562, 0.4872, 0.0335],
         [0.6919, 0.4250, 0.1349, 0.6589],
         [0.9980, 0.0083, 0.6583, 0.0916]]])

In [17]:
rnd_tensor.ndim

3

In [18]:
rnd_tensor.shape

torch.Size([2, 3, 4])

In [19]:
img_tensor = torch.rand(size=(3, 200, 200))
img_tensor

tensor([[[0.4970, 0.3274, 0.1673,  ..., 0.7506, 0.1977, 0.4584],
         [0.6289, 0.6824, 0.4448,  ..., 0.2014, 0.8314, 0.2140],
         [0.7323, 0.3363, 0.4263,  ..., 0.6256, 0.5023, 0.2365],
         ...,
         [0.5702, 0.6978, 0.5114,  ..., 0.2437, 0.5701, 0.1524],
         [0.9366, 0.0664, 0.4495,  ..., 0.9323, 0.3422, 0.0222],
         [0.0061, 0.0211, 0.0995,  ..., 0.2461, 0.6424, 0.1705]],

        [[0.9077, 0.2774, 0.3471,  ..., 0.4334, 0.0512, 0.9325],
         [0.9455, 0.1921, 0.7431,  ..., 0.2310, 0.7848, 0.4578],
         [0.9703, 0.3047, 0.1158,  ..., 0.1633, 0.3354, 0.1201],
         ...,
         [0.7650, 0.6669, 0.1342,  ..., 0.4894, 0.6472, 0.2855],
         [0.9408, 0.6155, 0.0155,  ..., 0.7543, 0.4044, 0.5994],
         [0.2718, 0.3298, 0.1246,  ..., 0.5574, 0.3658, 0.8627]],

        [[0.0548, 0.8440, 0.0542,  ..., 0.3222, 0.5705, 0.0144],
         [0.0461, 0.4142, 0.3751,  ..., 0.6258, 0.2542, 0.6905],
         [0.3848, 0.1612, 0.4472,  ..., 0.4728, 0.2976, 0.

In [20]:
img_tensor.ndim, img_tensor.shape

(3, torch.Size([3, 200, 200]))

In [21]:
img_tensor[0, 0]

tensor([4.9697e-01, 3.2743e-01, 1.6730e-01, 7.1026e-02, 3.5889e-01, 2.0809e-01,
        8.3725e-03, 3.3581e-01, 2.6525e-02, 7.6782e-01, 8.0905e-01, 4.7902e-01,
        9.4041e-01, 7.9427e-01, 5.6875e-02, 1.7926e-01, 1.9228e-01, 2.3145e-01,
        2.2871e-01, 9.5937e-01, 2.5445e-01, 5.8249e-01, 6.9742e-01, 6.9683e-01,
        8.3862e-01, 3.1233e-01, 3.4086e-01, 5.1587e-01, 1.4800e-01, 4.5556e-01,
        7.1367e-01, 8.9454e-01, 6.2885e-01, 1.1653e-01, 5.8837e-01, 5.2375e-01,
        9.7153e-01, 9.4913e-01, 5.1508e-01, 2.0568e-01, 9.0345e-01, 9.5795e-01,
        7.2745e-01, 4.7097e-01, 3.1320e-01, 2.0667e-01, 8.1832e-01, 8.0514e-01,
        4.1001e-01, 6.8361e-01, 1.2901e-01, 5.7743e-01, 7.4112e-01, 6.1211e-01,
        7.1213e-01, 1.1430e-01, 5.2031e-01, 3.9417e-01, 7.2116e-02, 6.4424e-01,
        8.3534e-01, 6.7936e-01, 1.2639e-01, 5.4103e-01, 2.0976e-01, 6.0797e-01,
        5.7438e-01, 3.0755e-01, 5.1293e-01, 1.8267e-01, 1.2140e-01, 7.7566e-01,
        3.3424e-01, 6.5785e-01, 5.7101e-

### Ones and zeroes

In [22]:
ones = torch.ones(size=(2, 2))
ones

tensor([[1., 1.],
        [1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
zeros = torch.zeros(size=(2, 2))
zeros

tensor([[0., 0.],
        [0., 0.]])

### Ranges and tensor like

In [25]:
range_tensor = torch.arange(0, 10, 2)
range_tensor

tensor([0, 2, 4, 6, 8])

In [26]:
like_tensor = torch.zeros_like(range_tensor)
like_tensor

tensor([0, 0, 0, 0, 0])

### Tensor datatypes

In [27]:
float_tensor = torch.tensor([2, 3, 4], dtype=torch.float32)
float_tensor

tensor([2., 3., 4.])

In [28]:
bool_tensor = torch.tensor([0, 3, 4], dtype=torch.bool)
bool_tensor

tensor([False,  True,  True])

In [29]:
int_tensor = float_tensor.type(torch.int32)
int_tensor.dtype

torch.int32

In [30]:
int_tensor

tensor([2, 3, 4], dtype=torch.int32)

In [31]:
int_tensor.device

device(type='cpu')

### Tensors operations

In [32]:
a_tensor = torch.tensor([1, 2, 3])

In [33]:
a_tensor + 10

tensor([11, 12, 13])

In [34]:
a_tensor * 10

tensor([10, 20, 30])

In [35]:
a_tensor - 10

tensor([-9, -8, -7])

In [36]:
a_tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [37]:
b_tensor = torch.tensor([4, 5, 6])

In [38]:
# element wise
a_tensor * b_tensor

tensor([ 4, 10, 18])

In [39]:
# matrix
torch.matmul(a_tensor, b_tensor)

tensor(32)

In [40]:
tensor_a = torch.tensor([[1, 2], 
                          [3, 4], 
                          [5, 6]])

In [41]:
tensor_a.shape

torch.Size([3, 2])

In [42]:
tensor_b = torch.tensor([[7, 10], 
                          [8, 11], 
                          [9, 12]])

In [43]:
tensor_b.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [44]:
tensor_b.T.shape

torch.Size([2, 3])

In [45]:
tensor_a @ tensor_b.T

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Tensor aggregation

In [46]:
tensor = torch.arange(1, 100, 3)

In [47]:
tensor.min()

tensor(1)

In [48]:
tensor.max()

tensor(97)

In [49]:
tensor = tensor.type(torch.float32)
torch.mean(tensor)

tensor(49.)

In [50]:
tensor.sum()

tensor(1617.)

In [51]:
tensor.argmin()

tensor(0)

In [52]:
tensor.argmax()

tensor(32)

In [53]:
tensor[13]

tensor(40.)

### Reshape, stack, squeeze, unsqueeze

In [54]:
tensor = torch.arange(1, 10)

In [55]:
tensor, tensor.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [56]:
new_tensor = tensor.reshape(3, 3)
new_tensor, new_tensor.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]), torch.Size([3, 3]))

In [57]:
v_tensor = tensor.view(1, 9)
v_tensor

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [58]:
v_tensor[:, 0] = 5
v_tensor

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [59]:
tensor

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
s_tensor = torch.stack([tensor, tensor], dim=1)
s_tensor

tensor([[5, 5],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5],
        [6, 6],
        [7, 7],
        [8, 8],
        [9, 9]])

In [61]:
s_tensor = torch.stack([tensor, tensor], dim=0)
s_tensor

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [62]:
tensor = torch.tensor([[1, 2, 3]])
tensor.shape

torch.Size([1, 3])

In [63]:
ss_tensor = torch.squeeze(tensor)
ss_tensor
ss_tensor.shape

torch.Size([3])

In [64]:
u_tensor = torch.unsqueeze(ss_tensor, dim=1)
u_tensor

tensor([[1],
        [2],
        [3]])

### Reproducibility

In [65]:
import torch

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
tensor_a = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
tensor_b = torch.rand(3, 4)

print(tensor_a)
print(tensor_b)
print(tensor_a == tensor_b)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### GPU usage

In [66]:
!nvidia-smi

Tue Feb 28 11:13:50 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P0    31W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [68]:
torch.cuda.is_available()

True

In [69]:
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

In [70]:
tensor = torch.tensor(data=[1, 2, 3], device = DEVICE)
tensor

tensor([1, 2, 3], device='cuda:0')

In [71]:
torch.cuda.device_count()

1

In [73]:
cpu_tensor = tensor.to("cpu")
cpu_tensor, cpu_tensor.device

(tensor([1, 2, 3]), device(type='cpu'))