# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
import torch
tensor_a = torch.rand(7, 7)
tensor_a

tensor([[0.6417, 0.9253, 0.4695, 0.0861, 0.0210, 0.0153, 0.3083],
        [0.6786, 0.7131, 0.3658, 0.8790, 0.2168, 0.6545, 0.9547],
        [0.3448, 0.0745, 0.6770, 0.9515, 0.2033, 0.5918, 0.7483],
        [0.8286, 0.0329, 0.8600, 0.8272, 0.3067, 0.5778, 0.1956],
        [0.7532, 0.6229, 0.6823, 0.0119, 0.6758, 0.2527, 0.9630],
        [0.6739, 0.4027, 0.0779, 0.7923, 0.5870, 0.0221, 0.9484],
        [0.5952, 0.5993, 0.3863, 0.2170, 0.2198, 0.5810, 0.6676]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
tensor_b = torch.rand(1, 7).T
tensor_a @ tensor_b

# Perform matrix multiplication 


tensor([[1.3741],
        [1.7652],
        [0.9301],
        [1.0888],
        [1.3788],
        [1.1654],
        [1.3704]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
SEED = 0
torch.manual_seed(SEED)
tensor_a = torch.rand(7, 7)

torch.manual_seed(SEED)
tensor_b = torch.rand(1, 7).T

m_tensor = tensor_a @ tensor_b
m_tensor, m_tensor.size()

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]), torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
CUDA_SEED = 1234
torch.cuda.manual_seed(CUDA_SEED)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [7]:
torch.manual_seed(99)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

tensor_a = torch.rand(size=(2,3)).to(device)
tensor_b = torch.rand(size=(2,3)).to(device)
tensor_a, tensor_b


Device: cuda


(tensor([[0.1033, 0.9702, 0.9481],
         [0.9787, 0.3268, 0.9200]], device='cuda:0'),
 tensor([[0.0503, 0.4583, 0.8608],
         [0.4882, 0.7981, 0.2011]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [11]:
m_tensor = torch.matmul(tensor_a, tensor_b.T)
m_tensor, m_tensor.size

(tensor([[1.2659, 1.0153],
         [0.9909, 0.9236]], device='cuda:0'), <function Tensor.size>)

### 8. Find the maximum and minimum values of the output of 7.

In [13]:
print(f"Min: {m_tensor.min()}")
print(f"Max: {m_tensor.max()}")

Min: 0.9235591888427734
Max: 1.2659226655960083


### 9. Find the maximum and minimum index values of the output of 7.

In [14]:
print(torch.argmin(m_tensor))
print(torch.argmax(m_tensor))

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [17]:
torch.manual_seed(7)

tensor = torch.rand(1, 1, 1, 10)
print(tensor, tensor.shape)

new_tensor = tensor.squeeze()
print(new_tensor, new_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
